version: 2.1
workflows:
  env-var-name:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:19.5.0
    steps:
      - checkout
      - run:
          my_name: "echo name of my enviromental variablest"
          command: |
            echo $MY_ENV_VAR
